# This file was generated by GoReleaser. DO NOT EDIT.
class Pgutil < Formula
  desc ""
  homepage ""
  url "https://github.com/sjansen/pgutil/releases/download/v0.1.0-alpha.1/pgutil_0.1.0-alpha.1_darwin_amd64.tar.gz"
  version "0.1.0-alpha.1"
  sha256 "51963052f45f0396674f05bd94fa9bd15f6bb445d046a3bf54a9fe61182010e1"

  def install
    bin.install "pgutil"
  end
end
