# This file was generated by GoReleaser. DO NOT EDIT.
class Pgutil < Formula
  desc ""
  homepage ""
  url "https://github.com/sjansen/pgutil/releases/download/v0.1.0-beta.2/pgutil_0.1.0-beta.2_darwin_amd64.tar.gz"
  version "0.1.0-beta.2"
  sha256 "f748622da40388147b83fe879fce14db6c3b347e62704a85fc5cb89d42785332"

  def install
    bin.install "pgutil"
  end
end
