# This file was generated by GoReleaser. DO NOT EDIT.
class Pgutil < Formula
  desc ""
  homepage ""
  url "https://github.com/sjansen/pgutil/releases/download/v0.1.0-alpha.2/pgutil_0.1.0-alpha.2_darwin_amd64.tar.gz"
  version "0.1.0-alpha.2"
  sha256 "b716419859ab1d2352d272cd626f507576a2ab257e019d2a8cc0bad9a8ab03a2"

  def install
    bin.install "pgutil"
  end
end
